version: '3'
services:
    meetyou-nginx:
        build:
            context: ./meetyou/docker/dev
            dockerfile: nginx.docker
        volumes:
            - ./meetyou:/app
        depends_on:
            - meetyou-php-fpm
        ports:
            - "8080:80"
    meetyou-php-fpm:
        build:
            context: ./meetyou/docker/dev
            dockerfile: php-fpm.docker
        volumes:
            - ./meetyou:/app
        environment:
            XDEBUG_CONFIG: "remote_connect_back=1; remote_enable=1;"
            PHP_IDE_CONFIG: "serverName=meetyou"
    meetyou-php-cli:
        build:
            context: ./meetyou/docker/dev
            dockerfile: php-cli.docker
        volumes:
            - ./meetyou:/app
            - composer:/root/.composer/cache
    meetyou-mysql:
        image: mysql:5.7.24
        volumes:
            - meetyou-mysql:/var/lib/mysql
        ports:
            - "33060:3306"
        environment:
            MYSQL_DATABASE: meetyou
            MYSQL_USER: meetyou
            MYSQL_PASSWORD: meetyou
            MYSQL_ROOT_PASSWORD: meetyou
    meetyou-node:
        image: node:latest
        volumes:
            - ./meetyou:/app
        working_dir: /app
volumes:
    composer:
    meetyou-mysql: