version: '3'
services:
  meetyou-nginx:
    image: ${REGISTRY_ADDRESS}/meetyou-nginx:${IMAGE_TAG}
    restart: always
    depends_on:
      - meetyou-php-fpm
    ports:
      - "8080:80"
  meetyou-php-fpm:
    image: ${REGISTRY_ADDRESS}/meetyou-php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_SECRET: ${MEETYOU_APP_SECRET}
      DATABASE_URL: mysql://meetyou:${MEETYOU_DB_PASSWORD}@meetyou-mysql:3306/meetyou
  meetyou-php-cli:
    image: ${REGISTRY_ADDRESS}/meetyou-php-cli:${IMAGE_TAG}
    environment:
      APP_SECRET: ${MEETYOU_APP_SECRET}
      DATABASE_URL: mysql://meetyou:${MEETYOU_DB_PASSWORD}@meetyou-mysql:3306/meetyou
  meetyou-mysql:
    image: ${REGISTRY_ADDRESS}/meetyou-mysql-master:${IMAGE_TAG}
    restart: always
    volumes:
      - meetyou-mysql:/var/lib/mysql
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: meetyou
      MYSQL_USER: meetyou
      MYSQL_PASSWORD: ${MEETYOU_DB_PASSWORD}
volumes:
  meetyou-mysql: